import React from "react";
import { auth } from "../../../../auth";
import db from "@/db/db";
import { Client, Project, Task } from "@prisma/client";
import TaskTable from "@/components/TaskTable";
import { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "@/icons/ArrowRight";
type TaskWithProject = Task & {
  Project: Project | null;
};

export const metadata: Metadata = {
  title: "All Tasks",
  description: "Generated by create next app",
};

const AllTaskPage = async () => {
  const session = await auth();
  const clientArr: Client[] = await db.client.findMany({
    where: {
      userId: session?.user?.id,
    },
  });

  return clientArr.length ? (
    <div className="flex flex-col gap-10 mt-6">
      {clientArr.map(async (c: Client) => {
        let specificClientData: TaskWithProject[] = await db.task.findMany({
          where: {
            clientName: c.name as string,
            userId: session?.user?.id,
          },
          include: {
            Project: true, // This includes the related project details
          },
        });
        console.log(specificClientData, "spec");
        if (!specificClientData.length) {
          return;
        }
        return (
          <div className="flex flex-col gap-3">
            <div className="flex justify-between">
              <h1 className="text-2xl">{c.name}</h1>
              <Link href={`/copyform/${c.id}`}>
                <ArrowRight />
              </Link>
            </div>
            <TaskTable data={specificClientData} />
          </div>
        );
      })}
    </div>
  ) : (
    <h1 className="text-center text-3xl mt-6">No Task to display</h1>
  );
};

export default AllTaskPage;
