import TaskNavbar from "@/components/Navbar";
import type { Metadata } from "next";
import "../globals.css";
export const metadata: Metadata = {
  title: "Task Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-screen dark">
      <TaskNavbar />
      <div className="max-w-[970px] px-4 mx-auto">{children}</div>
    </div>
  );
}
